import { StyleSheet } from 'react-native';
import { colors, spacing, radius, fontFamily } from '../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingHorizontal: spacing.lg,
  },
  scrollContent: {
    gap: spacing.sm + 2,
    paddingTop: spacing.huge,
    paddingBottom: 110,
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingBottom: spacing.xxxl,
    gap: spacing.sm,
  },
  bookmarkBtn: {
    width: 48,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bookmarkCircle: {
    width: 48,
    height: 48,
    backgroundColor: colors.surface,
    borderRadius: radius.full,
    justifyContent: 'center',
    alignItems: 'center',
  },
  adaptiveCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: spacing.md,
    gap: spacing.md,
    backgroundColor: colors.surface,
    borderWidth: 0.5,
    borderColor: colors.border,
    borderRadius: radius.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 3,
    alignSelf: 'stretch',
  },
  adaptiveLeft: {
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: spacing.md,
    width: 95,
  },
  adaptiveTitle: {
    fontSize: 24,
    fontWeight: '500',
    lineHeight: 29,
    color: colors.text,
    fontFamily: fontFamily.bodyMedium,
  },
  adaptiveArrowBtn: {
    width: 44,
    height: 44,
    backgroundColor: colors.primary,
    borderRadius: radius.full,
    justifyContent: 'center',
    alignItems: 'center',
  },
  adaptiveImage: {
    width: 249,
    height: 142.23,
    resizeMode: 'cover',
    borderRadius: radius.sm,
  },
  cardRow: {
    flexDirection: 'row',
    gap: spacing.sm + 2,
    alignSelf: 'stretch',
  },
  smallCard: {
    flex: 1,
    backgroundColor: colors.surface,
    borderWidth: 0.5,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing.md,
    gap: spacing.sm + 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 3,
  },
  smallCardContent: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: spacing.sm + 2,
  },
  smallCardTitle: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 19,
    color: colors.text,
    fontFamily: fontFamily.bodyMedium,
    alignSelf: 'stretch',
  },
  smallCardSubtitle: {
    fontSize: 14,
    fontWeight: '300',
    lineHeight: 17,
    color: colors.text,
    fontFamily: fontFamily.body,
    alignSelf: 'stretch',
  },
  smallCardArrowBtn: {
    width: 44,
    height: 44,
    backgroundColor: colors.surfaceSecondary,
    borderRadius: radius.full,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: 'flex-end',
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.xxl,
  },
  sourceModal: {
    width: '100%',
    backgroundColor: colors.surface,
    borderWidth: 0.5,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing.lg,
    gap: 33,
    elevation: 8,
  },
  sourceModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing.sm + 2,
  },
  sourceModalTitle: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 22,
    fontFamily: fontFamily.bodyMedium,
    color: colors.text,
  },
  sourceModalClose: {
    width: 24,
    height: 24,
    borderRadius: radius.md,
    backgroundColor: colors.textTertiary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sourceModalCloseIcon: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sourceModalCloseX: {
    fontSize: 14,
    color: colors.surface,
    fontWeight: '700',
    fontFamily: fontFamily.bodyBold,
  },
  sourceList: {
    gap: spacing.sm + 4,
  },
  sourceOption: {
    height: 48,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: radius.md,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sourceOptionText: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 22,
    fontFamily: fontFamily.bodyMedium,
    color: colors.text,
    textAlign: 'center',
  },
  selectionModal: {
    width: '100%',
    backgroundColor: colors.surface,
    borderWidth: 0.5,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing.lg,
    gap: 33,
    elevation: 8,
  },
  selectionModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing.sm + 2,
  },
  selectionModalTitle: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 22,
    fontFamily: fontFamily.bodyMedium,
    color: colors.text,
  },
  searchRow: {
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: radius.md,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 22,
    fontFamily: fontFamily.body,
    color: colors.text,
    padding: 0,
  },
  selectListRow: {
    flexDirection: 'row',
    gap: spacing.md,
    height: 260,
  },
  selectScroll: {
    flex: 1,
  },
  selectListGap: {
    gap: spacing.sm + 4,
  },
  selectItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    height: 48,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: radius.md,
  },
  selectItemSelected: {
    borderWidth: 2,
    borderColor: colors.primary,
  },
  selectItemText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 22,
    fontFamily: fontFamily.body,
    color: colors.text,
    marginRight: 12,
  },
  checkboxUnchecked: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: colors.textSecondary,
    borderRadius: 4,
  },
  checkboxChecked: {
    width: 24,
    height: 24,
    backgroundColor: colors.primary,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkMark: {
    fontSize: 14,
    color: colors.surface,
    fontWeight: '700',
    fontFamily: fontFamily.bodyBold,
  },
  scrollTrack: {
    width: 8.8,
    backgroundColor: colors.borderLight,
    borderRadius: radius.md,
    alignSelf: 'stretch',
  },
  scrollThumb: {
    position: 'absolute',
    left: 0,
    width: 8.8,
    height: 50.87,
    backgroundColor: colors.textTertiary,
    borderRadius: radius.md,
  },
  modalBottomBar: {
    height: 80,
    backgroundColor: colors.surfaceSecondary,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.sm + 4,
    paddingVertical: spacing.sm + 4,
    marginHorizontal: -spacing.lg,
    marginBottom: -spacing.lg,
    borderBottomLeftRadius: radius.md,
    borderBottomRightRadius: radius.md,
  },
  continueBtn: {
    width: '100%',
    height: 48,
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    justifyContent: 'center',
    alignItems: 'center',
  },
  continueBtnDisabled: {
    opacity: 0.5,
  },
  continueBtnText: {
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 22,
    fontFamily: fontFamily.bodyBold,
    color: colors.surface,
    textAlign: 'center',
  },
  pasteContentRow: {
    height: 321,
  },
  pasteInput: {
    flex: 1,
    padding: spacing.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: radius.md,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 22,
    fontFamily: fontFamily.body,
    color: colors.text,
  },
  tasksModal: {
    width: '100%',
    backgroundColor: colors.surface,
    paddingTop: spacing.lg,
    paddingHorizontal: spacing.lg,
    paddingBottom: 0,
    gap: 33,
    borderWidth: 0.5,
    borderColor: colors.border,
    borderRadius: radius.md,
    elevation: 8,
  },
  tasksModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing.sm + 2,
  },
  tasksModalTitle: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 22,
    fontFamily: fontFamily.bodyMedium,
    color: colors.text,
  },
  tasksModalBody: {
    gap: spacing.sm + 4,
  },
  tasksInputRow: {
    height: 48,
  },
  tasksInput: {
    flex: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: radius.md,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 22,
    fontFamily: fontFamily.body,
    color: colors.text,
  },
  tasksPresetRow: {
    flexDirection: 'row',
    gap: spacing.sm + 4,
  },
  taskPreset: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    height: 48,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: radius.md,
    justifyContent: 'center',
    alignItems: 'center',
  },
  taskPresetActive: {
    borderWidth: 3,
    borderColor: colors.primary,
  },
  taskPresetText: {
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 22,
    fontFamily: fontFamily.body,
    color: colors.textSecondary,
  },
  taskPresetTextActive: {
    color: colors.text,
    fontWeight: '500',
    fontFamily: fontFamily.body,
  },
  feedbackBtn: {
    alignSelf: 'center',
    marginTop: spacing.md,
    paddingVertical: 12,
    paddingHorizontal: spacing.lg,
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  feedbackBtnText: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.primary,
    fontFamily: fontFamily.bodyMedium,
  },
});
